### PR TITLE
ext: Increase the minimum PHP version to 7.1.

### PR DESCRIPTION
**Pull request by MrMage**
"inspired" by #276, thanks @remicollet!

### CODE REVIEW

**Comment by MrMage** [comment]
@bshaffer, @chingor13 PTAL (GitHub doesn't let me request a review from you).

**Comment by MrMage** [comment]
@bshaffer, @chingor13 friendly ping :-) The integration test failure is unrelated and has been fixed in #278.

**Comment by MrMage** [comment]
@bshaffer, @chingor13 Ping! Please review this.

**Review by bshaffer — APPROVED** [review]

**Comment by MrMage** [comment]
@bshaffer thanks for the review! Given that this is just one line, can you merge it without waiting for a review from @chingor13?

**Pull request merged**
