### PR TITLE
[#125] Adds support for zipkin span.kind tag.

### PR DESCRIPTION
**Pull request by jcchavezs**
Based on https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java#L169 and https://github.com/census-instrumentation/opencensus-go/blob/master/exporter/zipkin/zipkin.go#L104 we port the same functionality to obtain the `span.kind` for span.

Ping @chingor13

### CODE REVIEW

**Comment by jcchavezs** [comment]
I signed it!

**Comment by jcchavezs** [comment]
Apparently it is a docker failure. @chingor13 can you please rerun it?

**Comment by chingor13** [comment]
The test failed on its php 7.2 run on the phpunit tests.

`count(): Parameter must be an array or an object that implements Countable`
on `src/Trace/Exporter/ZipkinExporter.php:210`

**Comment by chingor13** [comment]
Actually, looks like a bug in the extension. It's returned span appears to return null instead of any empty array for `timeEvents` when none are set.

**Comment by jcchavezs** [comment]
Shall we just do `if ($span->timeEvents()) {` instead?

**Comment by chingor13** [comment]
That should work. 

I'll also fix the extension to make sure we return consistent data between the extension's span and the PHP library's span.

**Comment by jcchavezs** [comment]
@chingor13 this is green now.

**Pull request merged**
