### PR TITLE
chore: prepare 0.3.0 ext release

### PR DESCRIPTION
**Pull request by chingor13**

### CODE REVIEW

**Comment by Nowaker** [comment]
@chingor13 Can the PECL extension be released too? https://pecl.php.net/package/opencensus

**Comment by MrMage** [comment]
@chingor13 the PHP package is on version 0.7.0 already; wouldn't it make sense to share version numbers across package and extension? Also, did you test that the new package spec is correct and/or publish it to PECL?

**Comment by bshaffer** [comment]
@MrMage you make a good point, we should skip to `0.7.0`.

We are working on publishing it to PECL, but right now we're waiting to hear back from the PECL webmaster :-/

**Comment by Nowaker** [comment]
Thank you @bshaffer. Glad things are progressing!

**Comment by chingor13** [comment]
0.3.0 should be available on PECL

**Comment by MrMage** [comment]
> I previously had kept the versions separate because:
> 
> 1. PECL releases are more painful than tagging the PHP releases
> 2. The extension might have never reached 1.0.0 (while the PHP library would have) due to the complexity of the C code and being understaffed (the library won't hit 1.0.0 as opencensus' future is open telemetry).
> 
> Either keeping them separate or in sync is fine with me.

I understand the reasoning, but this had me quite confused, thinking that the PECL version of the extension was way more outdated than it actually is. And it seems like I am not the only one: https://github.com/census-instrumentation/opencensus-php/issues/275

Given that this package will likely never reach 1.0, so SemVer doesn't really apply, how about the following:

- re-release extension 0.3.0 once more as 0.7.0
- package-only changes will only bump the patch version, e.g. 0.7.1. They don't trigger a re-release of the extension on PECL.
- extension updates bump the minor version, e.g. 0.8.0. They are accompanied by an update of the package.

That way, package and extension should always be on the same minor; only the patch version could get out of sync.

**Pull request merged**
